# Generated by Django 2.2.6 on 2019-10-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seo_description',
            field=models.CharField(default='', help_text='\u200b\u200b\u200bThe SEO page description for the post.', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(default='', help_text='The SEO title for the post. Site owners can create a different title for the browser title bar.', max_length=60),
            preserve_default=False,
        ),
    ]
