version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: coding_vortex
    container_name: blog_web
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    env_file:
      - ./.env.example
    command: /start
    volumes:
      - media:/app/media/

  db:
    restart: always
    image: postgres:latest
    container_name: blog_db
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=coding_vortex
      - POSTGRES_PASSWORD=coding_vortex


volumes:
  postgres_data:
  media:
