#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py migrate
# python /app/manage.py collectstatic --noinput
gunicorn --bind 0.0.0.0:8000 --log-level DEBUG blog.wsgi:application
