# Generated by Django 2.2.6 on 2024-03-23 16:42

from django.db import migrations, models
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191004_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seo_description',
            field=models.CharField(help_text='The SEO page description for the post.', max_length=160, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.CharField(help_text='The SEO title for the post. Site owners can create a different title for the browser title bar.', max_length=60, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(blank=True, help_text='An array of strings that represent tags for the post', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
